### ISSUE TITLE
ReplaceGlobals cannot recover

### ISSUE THREAD

**Issue by breeswish** [pingcap/log#21]
The `ReplaceGlobals` sets a new global logger. However it doesn't provide ways to recover back the original logger. This makes it hard to be used in scenarios like tests, where a "SetGlobal" - "RevertGlobal" is a common pattern.

**Comment by tisonkun** [comment]
@breeswish a bit details - would you like a stack alike structure, or two slots switch of the now and the previous (like `cd -` in Mac)?

**Comment by breeswish** [comment]
> @breeswish a bit details - would you like a stack alike structure, or two slots switch of the now and the previous (like `cd -` on Mac)?

@tisonkun  From my experience loggers seems to be mostly return the original logger when swapping the global logger, like slog in Rust and zap. More specially, as pingcap/log is a wrapper over zap, maybe we can follow how `zap` does. Its `ReplaceGlobals` returns a function, which can be used to restore the logger.

**Comment by breeswish** [comment]
Implemented by #22
