### ISSUE TITLE
log.With shouldn't add caller skip

### ISSUE THREAD

**Issue by gozssky** [pingcap/log#32]
https://github.com/pingcap/log/blob/ca232912c9f31c181dc0b376133752bd41d27741/global.go#L66-L70
`log.With` shouldn't add caller skip, since it just returns a new logger without calling any function to print logs.

**Comment by gozssky** [comment]
@tiancaiamao @hawkingrei @bufferflies What do you think we should do to solve this issue? Since `log.With` is an exported function, someone may depend on this bug behavior. If we fix this bug, their program may go wrong. Or we can add a deprecated warning to this function?

**Comment by hawkingrei** [comment]
In tidb, we don't use this function. I think we can add a deprecated warning to this function.

**Comment by hawkingrei** [comment]
> In tidb, we don't use this function. I think we can add a deprecated warning to this function.

It mainly is used in br.
